### ISSUE TITLE
I occurred some some error in zepo integration But I can't recognize it.Please help me out .

### ISSUE THREAD

**Issue by babumolla** [danharper/sha256-hmac-examples#1]
Here I attached all my code in  PHP.

function demo_zepo()
{
// $email = "business@artpur.in";
// $password = "ImtiazKhan@123";
     $email = "zepotest@test.in";
     $password = "QFyFe8OIc6";
  $api_key = "8FB113771529399C1FE3667F4E5C9"; // ADD YOUR API KEY HERE
    $secret_key = "47BEDA5ED67496B1FAAE9D3D2B5A2"; // ADD YOUR SECRET KEY HERE
    $post_url = "http://api.couriers.vello.in/initiateShipmentRequest"; // TESTING ENVIRONMENT
    //$post_url = "http://api.couriers.zepo.in/initiateShipmentRequest"; // PRODUCTION ENVIRONMENT
    $strtoSign = "POST\n/initiateShipmentRequest";
    $strtoSign = urlencode($strtoSign);
    // echo $strtoSign;exit;
    $my_sign = hash_hmac("sha1", $strtoSign, $secret_key);
    $my_sign = base64_encode($my_sign);
    $header = "Authorization:SHIPIT"." ".$api_key.":".$my_sign;
    // echo $header;exit;
        $post_data= array(
        "email"=>$email,
        "password"=>$password
       );
          $post_json= json_encode($post_data);
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL,$post_url);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $post_json ); //Post Fields
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $headers = [
        'Accept-Encoding: gzip, deflate',
        'Accept-Language: en-US,en;q=0.5',
        'Cache-Control: no-cache',
        'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:28.0) Gecko/20100101 Firefox/28.0',
        'X-MicrosoftAjax: Delta=true',
        $header,
        'Content-Type:application/json',
    ];
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    $server_output = curl_exec ($ch);
    curl_close ($ch);
 print_r($server_output); exit;
 
}

**Comment by babumolla** [comment]
I got this issue ..If any one please help me??
{"success":false,"code":200,"message":"Invalid request"}

**Comment by danharper** [comment]
I'd recommend asking Zepo - this repo isn't related :)
